### PR TITLE
✨ #103 Improve filtering

### LINKED ISSUE #103: Improve usability on filter component
- [x] Add a cancel button on "vis straffer i tidsrom"
- [x] Add a way to add punishment types under "filter by punishment type". Right now it is only possible to cancel a specific punishment, or add all punishments("Velg alle")
- [x] Possible bug in Finn bruker, this filtering option does not work for me

### PR DESCRIPTION
**Pull request by VigdisIS**
Added a cancel button on "vis straffer i tidsrom", and an autocomplete search component to add punishment types to filter.

265e3a42b71fc0d9c733db5d6ae47736

da9d90036a44009d72674c5cb38a644d

Closes #103

### CODE REVIEW

File: frontend/src/components/punishments/PunishmentGrid.svelte [hunk 1]
```diff
@@ -16,7 +16,7 @@
 
   // TODO
   // Remove group_id once members from OW group from backend is implemented.
-  let group_id: number = 1;
+  let group_id: number = 3;
```
Comment (Terbau) [inline frontend/src/components/punishments/PunishmentGrid.svelte:19]: Selv om det kanskje ikke har så mye å si in the end, så er det greit å holde denne på `1` for nå. Gjør det også vanskelig å teste siden man må lage tre grupper.

**Review by Terbau — CHANGES_REQUESTED** [review]

File: frontend/src/components/filters/punishments/PunishmentTagSelect.svelte [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+    )}"
+    i18n="{myI18n}"
+    renderer="pun-blocks"
+    inputId="punishment"
+    bind:value
+    placeholder="Navn på straff"
+  />
+</div>
+
+<style lang="less">
```
Comment (annaiandresen) [inline frontend/src/components/filters/punishments/PunishmentTagSelect.svelte:59]:
```suggestion
<style lang="postcss">
```

just thinking since we're not really using less anyway. I think it might be better to use the color values we have in TW for consistency as well

**Comment by annaiandresen** [comment]
the autocomplete looks crisp tho

File: frontend/src/components/punishments/PunishmentGrid.svelte (hunk 1 above)
Comment (VigdisIS) [reply frontend/src/components/punishments/PunishmentGrid.svelte:19]: yeap! agreed!

**Comment by annaiandresen** [comment]
Screenshot 2022-10-18 at 13 12 31

has it always been like this?

**Comment by annaiandresen** [comment]
Screenshot 2022-10-18 at 13 14 01
also my punishments arent showing up sadge, is it like this for you?

**Comment by annaiandresen** [comment]
main works for me tho

**Review by annaiandresen — CHANGES_REQUESTED** [review]
see comments above^

**Comment by Terbau** [comment]
> Screenshot 2022-10-18 at 13 14 01
> 
> also my punishments arent showing up sadge, is it like this for you?
> Master works 🤨

They show up for me. It's probably an issue with how the punishments are stored in localStorage or something. In general there seems to be quite a few bugs surrounding the whole localStorage implementation. That should be tacked in another issue I guess, so on my end I'm ready to approve this PR.

**Comment by VigdisIS** [comment]
> > Screenshot 2022-10-18 at 13 14 01
> > also my punishments arent showing up sadge, is it like this for you?
> > Master works 🤨
> 
> They show up for me when testing this branch. It's probably an issue with how the punishments are stored in localStorage or something. In general there seems to be quite a few bugs surrounding the whole localStorage implementation. That should be tacked in another issue I guess, so on my end I'm ready to approve this PR.

Seems to be the same for me, made an issue #140 to fix this separately

**Review by Terbau — APPROVED** [review]
Then there is just one thing to say. LGTM.

**Comment by VigdisIS** [comment]
> Screenshot 2022-10-18 at 13 12 31
> 
> Something weird is happening with the sidebar

Should be resolved now (?)!

File: frontend/src/components/filters/Sidebar.svelte [hunk 3]
```diff
@@ -9,23 +9,23 @@
   import VvLogo from "./VvLogo.svelte";
 </script>
 
-<div class="sticky top-0 h-screen">
-  <div class="wrapper">
+<div class="wrapper sticky h-screen top-0">
```
Comment (annaiandresen) [inline frontend/src/components/filters/Sidebar.svelte:12]:
```suggestion
<div class="wrapper sticky top-0">
```

Screenshot 2022-10-19 at 11 10 35
it looks like this when I scroll down 😅 Removing h-screen works.

For later I think we maybe should make it fixed? so it wont be scrollable.

Comment (annaiandresen) [reply frontend/src/components/filters/Sidebar.svelte:12]: lol also sorry for being naggy lol, lgtm after this hahahah

**Review by annaiandresen — APPROVED** [review]
